### PR TITLE
Websocket implementation

### PR DESCRIPTION
**Pull request by Bluee1Bird**
implement websockets;

join a room atfter creation as a leader
join a room via roomcode
continuously update members of a waitingroom
start the game

sample page /websockets, sends and receives messages, sample implementation of timer count

### CODE REVIEW

**Comment by Bluee1Bird** [comment]
also, I changed the roomCode to a string 
RoomCoordinator now implements Singleton

**Comment by Bluee1Bird** [comment]
closes #65

**Comment by MarlenKuehn** [comment]
nice work

**Comment by MarlenKuehn** [comment]
für mich ist es ok zu mergen

**Pull request merged**
